version: "3.8"

services:

  bot:
    container_name: pypoca
    stdin_open: true
    tty: true
    build: .
    image: pypoca
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - pypoca-net
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
        reservations:
          cpus: 1
          memory: 256M

networks:
  pypoca-net:
