# This workflow will install Python dependencies, run lint and tests with a single version of Python

name: CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/*.yml"
      - "**.py"
      - ".dockerignore"
      - "Dockerfile"
      - "requirements.txt"
      - "setup.cfg"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Sort imports with isort
        run: |
          pip install isort
          isort pypoca/ tests/

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 pypoca/ --config=setup.cfg --count --show-source --statistics --benchmark

      - name: Format with brunette
        run: |
          pip install brunette
          brunette pypoca/ --config=setup.cfg --check

      - name: Find missing docstrings with interrogate
        run: |
          pip install interrogate
          interrogate pypoca/ --config=setup.cfg

      - name: Detect unused code with Vulture
        run: |
          pip install vulture
          vulture pypoca/ --ignore-names on_* --min-confidence 80

      - name: Test with pytest
        run: |
          pip install pytest pytest-asyncio pytest-cov
          pytest --cov=pypoca/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
