# This workflow will install Python dependencies, run lint and tests with a single version of Python

name: CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/*.yml"
      - "**.py"
      - ".dockerignore"
      - "Dockerfile"
      - "requirements/*.txt"
      - "setup.cfg"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/prod.txt') }}

      - name: Install
        run: make install

      - name: Lint
        run: make lint

      # - name: Tests
      #   run: make test

      - name: Codecov
        uses: codecov/codecov-action@v2
